version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running database migrations...
      - alembic upgrade head
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
  discard-paths: yes
